---
# playbook used to provision apps common to all my environments

- hosts: all
  roles:
    - facts
    - env_setup
    - aur_helper
    - virtualbox
    - vpn
    - docker
    - python
    - browsers
    - jetbrains
    - postman
    - vscodium
    - tools_webapp
    - tools_forensics
    - tools_recon
    - tools_cracking
    - tools_automation
    - tools_ad
    - tools_github
...
