---
# tasks file for gcc

- name: Install gcc tooling (Arch)
  yay:
    name: ['mingw-w64-gcc', 'gcc']
    state: present
  when: ansible_distribution == 'Archlinux'

- name: Install  gcc tooling (Debian)
  apt:
    name: ['gcc-mingw-w64-x86-64', 'gcc']
    state: present
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: 'Define role executed var {{ role_name }}_was_executed'
  set_fact:
    '{{ role_name }}_was_executed': true
    cacheable: true
