---
# tasks file for gcc

- name: Install gcc tooling (Arch)
  yay:
    name: ["mingw-w64-gcc", "gcc"]
    state: latest
  when: ansible_distribution == 'Archlinux'

- name: Install  gcc tooling (Debian)
  apt:
    name: ["gcc-mingw-w64-x86-64", "gcc"]
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"
