---
# tasks file for java

- name: Install gcc tooling (Arch)
  yay:
    name: ['jdk-openjdk']
    state: present
  when: ansible_distribution == 'Archlinux'

- name: Install  gcc tooling (Debian)
  apt:
    name: ['default-jdk']
    state: present
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: 'Define role executed var {{ role_name }}_was_executed'
  set_fact:
    '{{ role_name }}_was_executed': true
    cacheable: true
