---
# tasks file for tools_cracking

- name: Install cracking tool (Arch)
  yay:
    name: "{{ item }}"
    state: present 
  with_items:
    - blackarch/hydra
    - blackarch/johnny
    - blackarch/wordlistctl
    - blackarch/seclists
    - blackarch/mimikatz
    - blackarch/hashcat
    - blackarch/hash-identifier
    - extra/expect
  when: ansible_distribution == 'Archlinux'

- name: Install cracking tools (Debian)
  apt:
    name: "{{ item }}"
    state: present 
  become: true
  with_items:
    - hydra
    - john
    - seclists
    - mimikatz
    - hashcat
    - hash-identifier
    - whois
    - wordlists
  when: ansible_facts['os_family'] == "Debian"

- name: "Define role executed var {{ role_name }}_was_executed"
  set_fact:
    "{{ role_name }}_was_executed": true
    cacheable: true